### ISSUE TITLE
Cannot read property 'log' of null

### ISSUE THREAD

**Issue by damianoneill** [vishwanatharondekar/gitlab-cli#10]
Issue 

```
$ gitlab-cli browse
/usr/local/lib/node_modules/gitlab-cli/index.js:70
  logger.log('\nGetting base branch name');
        ^

TypeError: Cannot read property 'log' of null
    at getBaseBranchName (/usr/local/lib/node_modules/gitlab-cli/index.js:70:9)
    at browse (/usr/local/lib/node_modules/gitlab-cli/index.js:138:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/gitlab-cli/index.js:366:5)
    at Command.listener (/usr/local/lib/node_modules/gitlab-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/gitlab-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/gitlab-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitlab-cli/index.js:385:9)
    at Module._compile (module.js:571:32)
```

```
Running on OSX, installed using 

$ npm install https://github.com/vishwanatharondekar/gitlab-cli.git -g

$  uname -a
Darwin doneill-mbp 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64


$ git --version
git version 2.11.0

$ npm -v
4.0.5

$ node -v
v7.4.0
```

Both GITLAB_URL and GITLAB_TOKEN set.

**Comment by vishwanatharondekar** [comment]
Fixed by setting log instance. Can you please check by re-installing.

**Comment by damianoneill** [comment]
Thanks this worked.
