### ISSUE TITLE
when i use lab browse ,there are some problem.

### ISSUE THREAD

**Issue by hungry0** [vishwanatharondekar/gitlab-cli#62]
lab browse  (this  my command)

Error occured :
 { Error: Command failed: git config branch.release_vn_lua2_auto_convert_json_to_lua.remote

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git config branch.release_vn_lua2_auto_convert_json_to_lua.remote' }

**Comment by vishwanatharondekar** [comment]
Can you check if this is similar to https://github.com/vishwanatharondekar/gitlab-cli/issues/57

**Comment by hungry0** [comment]
yes,thanks

**Comment by vishwanatharondekar** [comment]
Closing this since it solves the problem. In hindsight, I need better errors for users so they understand what needs to be done.
